{% set name = "urdfdom-py" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/urdf_parser_py/archive/refs/tags/{{ version }}.tar.gz
  sha256: 35252568e329c86ee352c4285ad12dbd3430c88abbe441078687cd49f843f591



build:
  number: 4
  ignore_run_exports:
    - python
    - python_abi

requirements:
  build:
    - {{ compiler("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - setuptools                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyyaml
    - lxml

test:
  source_files:
    - test
  imports:
    - urdf_parser_py
  commands:
    - pip check
    - pytest ./test/ -v
    - test -f ${PREFIX}/share/ament_index/resource_index/packages/urdfdom_py  # [not win]
    - test -f ${PREFIX}/share/urdfdom_py/package.xml  # [not win]
    - test -f ${PREFIX}/lib/urdfdom_py/display_urdf  # [not win]
    - if not exist %LIBRARY_PREFIX%\\share\\ament_index\\resource_index\\packages\\urdfdom_py exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\urdfdom_py\\package.xml exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\urdfdom_py\\display_urdf.exe exit 1  # [win]
  requires:
    - pip
    - pytest
    - mock

about:
  home: https://github.com/ros/urdf_parser_py
  summary: Standalone URDF parser for Python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
