{% set name = "urdfdom-py" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/urdf_parser_py/archive/refs/tags/{{ version }}.tar.gz
  sha256: ea7ca336bf0e7d47048769634eb3ca63fc773cbdeef8ed2a7c38230151cc3b45
  patches:
    - 77.patch

build:
  number: 0
  ignore_run_exports:
    - python
    - python_abi

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyyaml
    - lxml

test:
  source_files:
    - test
  imports:
    - urdf_parser_py
  commands:
    - pip check
    - pytest ./test/ -v
    - test -f ${PREFIX}/share/ament_index/resource_index/packages/urdfdom_py  # [not win]
    - test -f ${PREFIX}/share/urdfdom_py/package.xml  # [not win]
    - test -f ${PREFIX}/lib/urdfdom_py/display_urdf  # [not win]
    - if not exist %LIBRARY_PREFIX%\\share\\ament_index\\resource_index\\packages\\urdfdom_py exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\urdfdom_py\\package.xml exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\urdfdom_py\\display_urdf.exe exit 1  # [win]
  requires:
    - pip
    - pytest
    - mock

about:
  home: https://github.com/ros/urdf_parser_py
  summary: 'Standalone URDF parser for Python.'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
